### ISSUE TITLE
Stopped worked just recently

### ISSUE THREAD

**Issue by BateauSD** [zhuzemin/pixiv_sort_by_popularity#11]
Hi there! It's a good plugin.
it worked fine for the last 4 days but now it looks like something happened.
![image](https://user-images.githubusercontent.com/13334848/105614943-74fe9700-5e18-11eb-801f-72e69cd523b3.png)

**Comment by BateauSD** [comment]
It's worked now. So it's was just expired premium?..

**Comment by zhuzemin** [comment]
> 
> 
> Hi there! It's a good plugin.
> it worked fine for the last 4 days but now it looks like something happened.
> ![image](https://user-images.githubusercontent.com/13334848/105614943-74fe9700-5e18-11eb-801f-72e69cd523b3.png)

I test just now,script  work fine, 
make sure you are using version 1.28, 
and  script rely on cloudflare worker, so make sure  https://proud-surf-e590.zhuzemin.workers.dev is visitable. 
*sholud respond '400--'

**Comment by BateauSD** [comment]
> > Hi there! It's a good plugin.
> > it worked fine for the last 4 days but now it looks like something happened.
> > ![image](https://user-images.githubusercontent.com/13334848/105614943-74fe9700-5e18-11eb-801f-72e69cd523b3.png)
> 
> I test just now,script work fine,
> make sure you are using version 1.28,
> and script rely on cloudflare worker, so make sure https://proud-surf-e590.zhuzemin.workers.dev is visitable.
> *sholud respond '400--'

Yes version 1.28, just it didn't worked some time. Thank you.
