### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ccccmhq** [zhuzemin/pixiv_sort_by_popularity#6]
hi! i absolutely love this script but it doesn't seem to be working anymore? i get stuck with a blank page once I click sort by popularity

**Comment by zhuzemin** [comment]
> 
> 
> hi! i absolutely love this script but it doesn't seem to be working anymore? i get stuck with a blank page once I click sort by popularity

fixed

**Comment by ccccmhq** [comment]
thank you!
